on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
    paths-ignore:
      - 'multimodal/**'
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'multimodal/**'

permissions:
  id-token: write
  contents: read
  attestations: read

name: CI Test, Typecheck
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test
  cancel-in-progress: true
env:
  CI: true
  NODE_OPTIONS: --max-old-space-size=8192
  HUSKY: 0

jobs:
  test:
    name: Test & Typecheck
    if: github.repository == 'bytedance/UI-TARS-desktop'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache turbo
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install pnpm
        uses: pnpm/action-setup@7088e561eb65bb68695d245aa206f005ef30921d # v4.1.0
        with:
          version: 9.10.0
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: browser-actions/setup-chrome@c785b87e244131f27c9f19c1a33e2ead956ab7ce # v1
        with:
          chrome-version: 120
          install-dependencies: true
      - name: Install dependencies
        run: pnpm install
      - name: Run typecheck
        run: npm exec turbo run typecheck
      - name: Run test
        run: npm exec turbo run coverage
      - name: Upload coverage data
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          fail_ci_if_error: true
          disable_search: true
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: false
